#! /bin/bash

#   -w, --width=<int>         output image width (default is 256)
#   -h, --height=<int>        output image height (default is 256)
#   -a, --antialias=<int>     antialias level (default is 1), valid values {1,2,4,8,16}
#   -r, --resolution=<int>    render resolution (default is 128)
#   --bg_red=<double>         background color for red channel (default is 0.0)
#   --bg_green=<double>       background color for green channel (default is 0.0)
#   --bg_blue=<double>        background color for blue channel (default is 0.0)
#   -d, --depth=<double>      water depth (default is 1.5)
#   -i, --intensity=<double>  light intensity (default is 0.05)
#   -a, -f, --amp_filter=<double> amplitude filter (default is 30.0)
#   -f, -f, --freq_filter=<double> frequency filter (default is 1.5)
#   -t, -f, --time_filter=<double> time filter (default is 32.0)
#   -l, --length=<int>        animation length (default is 32)
#   -s, --start=<int>         start frame to render (default is 1)
#   -e, --end=<int>           end frame to render (default is same as animation length)
#   -o <output>               output file (default is "CausticsRender_%03d")
#   --bmp                     save output in BMP file format
#   -v, --verbose, --debug    verbose messages
#   --help                    print this help and exit
#   --version                 print version information and exit

WIDTH=512
HEIGHT=512
ANTIALIAS=2
RESOLUTION=1024
RED=0.0
GREEN=0.0
BLUE=0.0
DEPTH=10.0
INTENSITY=0.05
AMP_FILTER=30.0
FREQ_FILTER=1.5
TIME_FILTER=32.0
LENGTH=1
START=1
END=${LENGTH}
OUTPUT="test_%03d"

wine CausticsGeneratorCmd.exe -w ${WIDTH} -h ${HEIGHT} -a ${ANTIALIAS} -r ${RESOLUTION} --bg_red=${RED} --bg_green=${GREEN} --bg_blue=${BLUE} -d ${DEPTH} -i ${INTENSITY} --amp_filter=${AMP_FILTER} --freq_filter=${FREQ_FILTER} --time_filter=${TIME_FILTER} -l ${LENGTH} -s ${START} -e ${END} -o ${OUTPUT}
